### ISSUE TITLE
调用zhipuai api时传入错误参数api_key

### ISSUE THREAD

**Issue by Lealand23231513** [arcstep/langchain_zhipuai#1]
<img width="704" alt="5dbfa7b726797a2467f939a93223a6f" src="https://github.com/arcstep/langchain_zhipuai/assets/112753445/4d659533-2342-439a-b744-e5adbd34c39b">
如上图，此处api_key应删除，否则会导致在初始化ChatZhipuAI时传入api_key后调用报错

**Comment by arcstep** [comment]
非常感谢，已经按您的建议修改好了，要更新到 v4.0.10
