### ISSUE TITLE
缺少引入FunctionMessage

### ISSUE THREAD

**Issue by fhawktuo** [arcstep/langchain_zhipuai#4]
![image](https://github.com/arcstep/langchain_zhipuai/assets/99779704/96048e05-9a94-4d14-bade-3c4e26022a4a)

_convert_message_to_dict 方法使用了FunctionMessage,
但是在import的时候没有引入。

**Comment by arcstep** [comment]
https://github.com/arcstep/langchain_zhipuai/blob/e55af13eed673bc409ffdb143030e6cc0b2af27c/langchain_zhipu/chat.py#L35-L36

感谢提醒！

**Comment by fhawktuo** [comment]
> https://github.com/arcstep/langchain_zhipuai/blob/e55af13eed673bc409ffdb143030e6cc0b2af27c/langchain_zhipu/chat.py#L35-L36
> 
> 感谢提醒！

多谢写的这个包，减少不少工作。
可以麻烦更新一下pypi上面的包嘛？

**Comment by arcstep** [comment]
> > https://github.com/arcstep/langchain_zhipuai/blob/e55af13eed673bc409ffdb143030e6cc0b2af27c/langchain_zhipu/chat.py#L35-L36
> > 
> > 感谢提醒！
> 
> 多谢写的这个包，减少不少工作。 可以麻烦更新一下pypi上面的包嘛？

已经更新到 [langchain_zhipu@4.0.20](https://pypi.org/project/langchain_zhipu/4.0.20/)
