### ISSUE TITLE
这个仓库相关的库配置是什么？langchain版本是什么？

### ISSUE THREAD

**Issue by leofinch0824** [arcstep/langchain_zhipuai#7]
参考你的代码，运行下面的代码出现错误
```python
from langchain_zhipu import ChatZhipuAI
from langchain_core.callbacks import BaseCallbackHandler
import os

API_KEY = os.getenv("GLM_API_KEY")

llm = ChatZhipuAI(
    api_key=API_KEY,
    model="glm-3-turbo",
    temperate=0.7, )

llm.invoke("你是什么模型？")
```
报错内容：AttributeError: 'ChatZhipuAI' object has no attribute 'return_type'

**Comment by arcstep** [comment]
似乎是KEY的问题。

你先试试把 GLM_API_KEY 修改为 ZHIPUAI_API_KEY。

**Comment by arcstep** [comment]
包的配置在这里：

https://github.com/arcstep/langchain_zhipuai/blob/412a6ff8614e50c50bbc37134533b3a3fd9baa3e/pyproject.toml#L12-L17

**Comment by leofinch0824** [comment]
谢谢，不是API设置的问题，是部分依赖的版本有冲突导致的，已解决

**Comment by xeon-ye** [comment]
> 谢谢，不是API设置的问题，是部分依赖的版本有冲突导致的，已解决

想知道怎么解决的，遇到了同样的问题
