### ISSUE TITLE
遇到 'ChatZhipuAI' object has no attribute 'return_type'**的问题

### ISSUE THREAD

**Issue by xeon-ye** [arcstep/langchain_zhipuai#8]
版本4.1,2,执行下边的代码会遇到 'ChatZhipuAI' object has no attribute 'return_type'**的问题
from langchain_zhipu import ChatZhipuAI
import os

API_KEY = os.getenv("ZHIPU_API_KEY")

llm = ChatZhipuAI(
    api_key=API_KEY,
    model="glm-3-turbo",
    temperate=0.7, )

llm.invoke("你是什么模型？")
错误信息：
**anaconda3\envs\py310\lib\site-packages\langchain_zhipu\http\base.py", line 125, in lc_attributes
    if self.return_type:
AttributeError: 'ChatZhipuAI' object has no attribute 'return_type'**

**Comment by xeon-ye** [comment]
注释这两行就可用了，没仔细看逻辑      
  **# if self.return_type:
        #     attributes["return_type"] = self.return_type**

**Comment by arcstep** [comment]
多谢了！
我已经将修改后的版本升级到 [PyPi v4.1.3](https://pypi.org/project/langchain_zhipu/)

这部份代码一般是为了序列化的时候使用，不过 `return_type` 这个属性并不需要被序列化，被我直接在新版本中移除了。
